name: LiteLookup CI

on:
  push: 
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      