name: LiteLookup CI

on:
  push: 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip  & python -m pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Generate CHANGELOG and Set Version
        run: |
          chmod +x scripts/chlog.sh
          ./scripts/chlog.sh
          echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
        env:
          GTHUB_WORKSPACE: ${{ github.workspace }}

      - name: Debug setup.py
        run: cat setup.py
  
      - name: Install Twine
        run: python -m pip install twine

      - name: Install setuptools
        run: pip install setuptools

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload dist/*

      