---
name: LiteLookup CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      UV_SYSTEM_PYTHON: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependecy-glob: "uv.lock"

      - name: Install the project
        run: |
          uv lock
          uv sync --locked --all-extras --dev

      - name: Run tests
        run: uv run pytest

